FROM python:3.12


#INSTALL SSJ CLIENT 
RUN apt-get update && apt-get install -y openssh-client

#SET ENVIROMENT VARIABLES 
ENV PYTHONUNBUFFERED 1

#SET WORKING DIRECTORY
WORKDIR /app 

#copiamos el archivo de requerimientos.txt 
COPY requirements.txt /app/requirements.txt

#instalamos dependencias de python 
RUN pip install -r requirements.txt 

#compiamos la aplicacion a el directorio de trabajo de docker 
COPY . /app 

# Iniciarmos el ssh 
CMD python manage.py runserver 0.0.0.0:8000