# Generated by Django 4.2.19 on 2025-02-25 18:17

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('imagenes', models.ImageField(upload_to=apps.blog.models.categoria_images_directory)),
                ('slug', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=256)),
                ('contenido', models.TextField()),
                ('imagenes', models.ImageField(upload_to=apps.blog.models.blog_images_directory)),
                ('keywords', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.categoria')),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(1, 'h1'), (2, 'h2'), (3, 'h3'), (4, 'h4'), (5, 'h5'), (6, 'h6')])),
                ('order', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headings', to='blog.post')),
            ],
        ),
    ]
