# Generated by Django 4.2.19 on 2025-02-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heading',
            options={'ordering': ['order']},
        ),
    ]
